void login(void);
void reg(void);
void ticket_booking();
void viewAll_route();
void travel_histroy();
void insect_route();
int ac();
int seater();
int sleeper();
void admin();
void call();
void buses();
char ad_user[20], ad_pass[20];
