void login(void);
void ticket_booking();
void viewAll_route();
void travel_histroy();
void insect_route();
int ac();
int seater();
int sleeper();
void call();
void buses();
void FindRoute();
char Arrival(char *pp);
char Depature(char *des);
char ad_user[20], ad_pass[20];
